# d2 --theme=300 --dark-theme=200 -l elk --pad 0 ./input.d2

Diagrama de Sequência: {
  shape: sequence_diagram
  usuario: Usuário {shape: person}
  frontend: Interface do Usuário
  backend: Servidor
  banco: Banco de Dados Remoto
  drone: Drone

  Interação do Sistema: {
    usuario -> frontend: acessa a interface
    frontend -> backend: requisita dados
    backend -> banco: consulta dados
    banco -> backend: retorna dados
    backend -> frontend: retorna dados
    frontend -> usuario: exibe dados
  }
  Interação com o Drone: {
    usuario -> drone: envia comando
    drone -> backend: requisita autorização
    backend -> banco: consulta autorização
    banco -> backend: retorna autorização
    backend -> drone: autoriza comando
    drone -> usuario: executa comando
    drone -> backend: envia status
    backend -> banco: atualiza status
    banco -> backend: confirma atualização
    backend -> usuario: confirma execução
    usuario -> drone: solicita status
  }
  Interação com o Drone: {
    usuario -> drone: envia comando
    drone -> backend: requisita autorização
    backend -> banco: consulta autorização
    banco -> backend: retorna autorização
    backend -> drone: autoriza comando
    drone -> usuario: executa comando
    drone -> backend: envia status
    backend -> banco: atualiza status
    banco -> backend: confirma atualização
    backend -> usuario: confirma execução
    usuario -> drone: solicita status
  }
  Interação com o Drone: {
    usuario -> drone: envia comando
    drone -> backend: requisita autorização
    backend -> banco: consulta autorização
    banco -> backend: retorna autorização
    backend -> drone: autoriza comando
    drone -> usuario: executa comando
    drone -> backend: envia status
    backend -> banco: atualiza status
    banco -> backend: confirma atualização
    backend -> usuario: confirma execução
    usuario -> drone: solicita status
  }
}
